# # key name and database_name are the same and are the paths to the text files of the textbook
# rudin_chapter1/tex:
#   base_name: "rudin_chapter1"
#   database_name: "rudin_chapter1/tex"
#   base_path: "~/data/maf_data"

#   # - Where the raw text files are stored
#   data_dir: "{base_path}/textbooks/rudin/{database_name}"  

#   # - Where extractions are stored
#   cache_dir: "{base_path}/extractions/{database_name}/.cache"
#   # function_cache_dir: "{base_path}/extractions/{database_name}/.cache/function_cache"
#   generative_index_path: "{base_path}/extractions/{database_name}/generative_indexes"

#   # - Gold extractions file, The gold_extractions_file refers to a file containing the ground truth extractions for the documents in the dataset. dict with file_j -> att_i: val_i
#   # gold_extractions_file: "{base_path}/textbooks/rudin/{base_name}/gold_attributes.yaml" 
#   gold_extractions_file: "{base_path}/textbooks/rudin/gold_attributes.yaml" 
#   gold_attributes_file: "{base_path}/textbooks/rudin/gold_attributes.yaml" 

#   # - Topic
#   topic: "rudin text generated by mathpix https://snip.mathpix.com/search"

# # key name and database_name are the same and are the paths to the text files of the textbook
# rudin_real_analysis/tex:
#   base_name: "rudin_real_analysis"
#   database_name: "rudin_real_analysis/tex"
#   base_path: "~/data/maf_data"

#   # - Where the raw text files are stored
#   data_dir: "{base_path}/textbooks/rudin/{database_name}"  

#   # - Where extractions are stored
#   cache_dir: "{base_path}/extractions/{base_name}/.cache"
#   # function_cache_dir: "{base_path}/extractions/{database_name}/.cache/function_cache"
#   generative_index_path: "{base_path}/extractions/{base_name}/generative_indexes"

#   # - Gold extractions file, The gold_extractions_file refers to a file containing the ground truth extractions for the documents in the dataset. dict with file_j -> att_i: val_i
#   # note might be gold attributes as a hack
#   # gold_extractions_file: "{base_path}/textbooks/rudin/{database_name}/gold_attributes.yaml" 
#   gold_extractions_file: "{base_path}/textbooks/rudin/gold_attributes.yaml" 
#   gold_attributes_file: "{base_path}/textbooks/rudin/gold_attributes.yaml" 

imo_md_clean_v2.0_287:
  base_name: "imo_md_clean_v2.0_287"
  # database_name: "rudin_real_analysis/tex"
  # base_path: "~/data/maf_data/imo_md_clean_v2.0_287"

  # - Where the raw text files are stored
  data_dir: "~/data/maf_data/imo_md_clean_v2.0_287"  

  # - Where extractions are stored
  cache_dir: "~/data/extractions/{base_name}/.cache"
  function_cache_dir: "~/data/extractions/{base_name}/.cache/function_cache"
  generative_index_path: "~/data/extractions/{base_name}/generative_indexes"

  # - Gold extractions file, The gold_extractions_file refers to a file containing the ground truth extractions for the documents in the dataset. dict with file_j -> att_i: val_i
  gold_extractions_file: "~/evaporate/configs/gold_attributes/imo/gold_attributes.yaml"
  gold_attributes_file: "~/evaporate/configs/gold_attributes/imo/gold_attributes.yaml" 